### ISSUE TITLE
Simpler command for board ID

### ISSUE THREAD

**Issue by petef4** [upekkha/AppleHardwareTest#10]
Actually this is mainly to say thanks for your resource. It enabled me to run diagnostics on my MacBook Pro. As a result I now know that I have a known problem with the NVIDIA GeForce 8600M GT graphics processor: https://support.apple.com/en-gb/HT203254. Apple will no longer fix it but if it gets worse I will attempt this rather daunting repair: http://computers.tutsplus.com/tutorials/how-to-cook-your-mac--mac-45148. In the meantime in Systems Preferences -> Sharing I have turned on Screen Sharing and Remote Login so that if the video becomes unusable I will still be able to gain control.

The command for board ID does not need `grep`, `awk` can manage:

    ioreg -l | awk -F\" '/board-id/ { print $4 }'

**Comment by upekkha** [comment]
Thanks for your feedback. The simpler command was merged in 50d529496e767f3ea3e5dd273b626cafbe5d0daa.

**Comment by JohnGEyles** [comment]
Thanks for providing this, but I'm having an issue getting it to work.  I restored the diagnostics by doing (in Unix shell):

cp -r [foo]/System/Library/CoreServices/.diagnostics /System/Library/CoreServices/.

... where 'foo" is the dmg file downloaded here and mounted.

But when I restart with 'D' depressed, the machine just starts up normally.   No special diagnostic environment.

Thanks for any advice.

**Comment by petef4** [comment]
I've observed this too. For the last few days i've been trying to run
diagnostics but have been unable to launch them. I'm thinking that El
Capitan has changed something. Several others are asking about this but
I've yet to see a solution.

-- 
Pete

**Comment by JohnGEyles** [comment]
Did you see my follow-up about a bootable thumb-drive ?

On Oct 13, 2015 5:10 PM, "petef4" <notifications@github.com> wrote:
>
> I've observed this too. For the last few days i've been trying to run
> diagnostics but have been unable to launch them. I'm thinking that El
> Capitan has changed something. Several others are asking about this but
> I've yet to see a solution.
>
> --
> Pete
>
> On 13 October 2015 at 18:48, JohnGEyles <notifications@github.com> wrote:
>
> > Thanks for providing this, but I'm having an issue getting it to work. I
> > restored the diagnostics by doing (in Unix shell):
> >
> > cp -r [foo]/System/Library/CoreServices/.diagnostics
> > /System/Library/CoreServices/.
> >
> > ... where 'foo" is the dmg file downloaded here and mounted.
> >
> > But when I restart with 'D' depressed, the machine just starts up
> > normally. No special diagnostic environment.
> >
> > Thanks for any advice.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
https://github.com/upekkha/AppleHardwareTest/issues/10#issuecomment-147792415

**Comment by JohnGEyles** [comment]
Actually, that follow-up was to one of the "issues" on that same thread.
 Anyhow, the bootable thumb-drive worked very well.
