### ISSUE TITLE
Diagnostic tools don't start iMac7,1 Mac-F4238CC8 

### ISSUE THREAD

**Issue by penguin02007** [upekkha/AppleHardwareTest#11]
Followed the steps but I am unable to boot to AHT with D or Option+D on **Mac-F4238CC8** image: (**edited: Code has been updated and is now working**)

`curl http://download.info.apple.com/Apple_Hardware_Test/018-3169-A.dmg -o ~/Downloads/C018-3169-A.dmg`
`hdiutil attach ~/Downloads/C018-3169-A.dmg`
`rsync -avP /Volumes/AppleHardwareTest/System/Library/CoreServices/.diagnostics /System/Library/CoreServices`
`hdiutil detach /Volumes/AppleHardwareTest && rm /tmp/018-3169-A.dmg`

**Comment by 3ji7ja0jb9c** [comment]
@penguin02007, I think you copied to wrong location:
/System/Library/CoreServices/.diagnostics/System/Library/CoreServices/.diagnostics/…

Try:
cp -R /Volumes/AppleHardwareTest/System/Library/CoreServices/.diagnostics /System/Library/CoreServices

**Comment by penguin02007** [comment]
That's it. Thank you! I have updated my post in case everyone ran into the similar issue.
