### ISSUE TITLE
there's no .diagnostics file in the coreservices folder

### ISSUE THREAD

**Issue by pclafferty2147** [upekkha/AppleHardwareTest#14]
what does it mean "use the contents to restore the /System/Library/CoreServices/.diagnostics folder"?

I download the .dmg, but with no .diagnostics file in the core services folder I don't know what to do next?

please help!

**Comment by upekkha** [comment]
By default, the Finder does not show files or folders when their name starts with a dot (eg .diagnostics). You can easily find instructions on the web to make them visible (search for 'Finder AppleShowAllFiles'), or use the `ls -la` command in the terminal.

**Comment by schroef** [comment]
Using shift-cmd+g to access this folder and also get same error "the folder cant be found"

![Screen Shot 2021-09-09 at 14 28 18](https://user-images.githubusercontent.com/6923008/132742421-bc1cd216-1cc8-49e1-8dfb-17ad6096357d.png)
