### ISSUE TITLE
Duplicate entry in IMac list

### ISSUE THREAD

**Issue by ael-code** [upekkha/AppleHardwareTest#15]
In [IMac list](https://github.com/upekkha/AppleHardwareTest#imac) there are two entries with the same text that points to different links

```
* [iMac10,1      Mac-F2268CC8](http://download.info.apple.com/Apple_Hardware_Test/022-4451-A.dmg)
* [iMac10,1      Mac-F2268CC8](http://download.info.apple.com/Apple_Hardware_Test/022-4647-A.dmg)
```

**Comment by upekkha** [comment]
Indeed. Also duplicate issue. See #6 or #7.

**Comment by ael-code** [comment]
@upekkha wrote:
> Unfortunately I don't know the difference between the various AHT. I simply list all the packages I could find, hoping that at least one should work for a given hardware.

I think that it will be better if you put this explanation inside the doc.
One other solution could be to explicitly list all variant codes of the same hardware.

**Comment by upekkha** [comment]
You're right, it's now mentioned in the readme. 8792decf1ff079274df5ddf58e2620f1ccaf9075
