### ISSUE TITLE
iMac 11,3 could not get 'D' key or Option key to recognize Toast burnt DMG

### ISSUE THREAD

**Issue by cartographer4** [upekkha/AppleHardwareTest#17]
I made a Toast burnt DMG copy to my CD and it would not recognize the hardware test on the  CD.  Should be no trouble as it is only 100 some odd MB, and the files look exactly the same as they did on the original DMG.

I copied with Carbon Copy Cloner to a USB Flash drive formatted HFS+ Journalled GUID, and the same problem.    Now I'm reading on the forum suggestions to post .efi file to the library folder.   Are you talking the hard drive library folder?  What if you have more than one partition with more than one operating system on the computer.  I.e. I have three partitions on my computer.  Would that make hardware test not work?   Do I need to put it on the Library folder of the last booted operating system?

**Comment by RedOrion** [comment]
From what I know, it prefers to be on the last booted OS. Are you holding down the D key on boot?

**Comment by upekkha** [comment]
You may try to run the AHT from a bootable USB stick, as described in the Readme.
