### ISSUE TITLE
CoreServices permission

### ISSUE THREAD

**Issue by Clementinox** [upekkha/AppleHardwareTest#18]
Is there a way to copy the .diagnostics folder to Coreservices folder.
I have tried using terminal with cp -R and sevral commands but still getting No such file or directory error even tho everything is correct 

sudo cp -R /Volumes/AHTCOne/System/Library/CoreServices/.diagnostics /System/Library/CoreServices

I tried changing permissions of the folder nothing works. please help

**Comment by upekkha** [comment]
The System Integrity Protection (SIP) of OS X 10.11 El Capitan no longer allows writing to system folders. You may try to run the AHT from a bootable USB stick.
