### ISSUE TITLE
Missing Macbook Air 6,1+6,2+7,1+7,2 

### ISSUE THREAD

**Issue by opragel** [upekkha/AppleHardwareTest#20]
I found these, but I'm not sure how to verify what Macbook Air they're for. Guessing it might be "MacbookAir6,1", "MacbookAir6,2", and "MacbookAir7,1"+"MacbookAir7,2" based on the way that MacbookAir3,1 and MacbookAir3,2 were separated.

http://download.info.apple.com/Apple_Hardware_Test/022-5879-A.dmg
http://download.info.apple.com/Apple_Hardware_Test/022-5882-A.dmg
http://download.info.apple.com/Apple_Hardware_Test/022-6031-A.dmg

**Comment by upekkha** [comment]
These AHT dmg files are already included in my list. My guess would be that Macbook Air 6,1 and later use the newer AppleDiagnostics, as they were introduced after mid 2013, and therefore don't have any AHT.
