### ISSUE TITLE
Cannot find bootable usb

### ISSUE THREAD

**Issue by falconmick** [upekkha/AppleHardwareTest#23]
Hey guys.  2 problems for my mac mini 2009. 

1 I can't seem to get my mac

**Comment by falconmick** [comment]
Sorry, on my phone and I fat fingered submit.. Apparently I can't edit on phone so I'll try again here. 

Hey guys. 2 problems for my mac mini 2009.

1 I can't seem to get my mac to start in choose boot disk mode... I've held they key your supposed to (options from memory) but it doesn't enter the screen to choose device. Also I  told my mac to start in choose a disk to boot from mode (inside startup disk options)  but I just get a screen with a floating sign that does nothing. 

2. My use doesn't show  up in the list of bootable devices inside the startup disk options screen.  :(

Any help appreciated
Michael

**Comment by limeblack** [comment]
Are you using an apple keyboard?

**Comment by falconmick** [comment]
Issue was wireless keyboard not being supported. Moved to wired and issue resolved
