### ISSUE TITLE
Cannot write files to directory

### ISSUE THREAD

**Issue by nunocalaim** [upekkha/AppleHardwareTest#24]
I try to move the contents to /System/Library/CoreServices/.diagnostics

but it won't allow me to do it even with sudo.
Any thoughts?

**Comment by nunocalaim** [comment]
Apparently I need to go into recovery mode and disable something that is there to protect my computer... Is there an easier way?

**Comment by upekkha** [comment]
Duplicate of #18, now also explained in the Readme ba982211e8ad4aa4ff99010dc481fb486af78511

**Comment by kupietools** [comment]
My System Integrity Protection is disabled and it still won't let me copy. Instructions would be preferable to no instructions.
