### ISSUE TITLE
Determining AHT By Mac Model

### ISSUE THREAD

**Issue by nated099** [upekkha/AppleHardwareTest#25]
I'm having a little difficulty. Most sites tell you to login to os x and go to your system details to get your version i.e. (2,3) or whatever. For machines that don't boot, is there a way to determine the AHT version by model number and year? I work on alot of Macs so i've been just downloading each AHT version for the mac (if its macbook air i download all of the AHT's for air and try each one individually). Any help on this matter would be appreciated.

**Comment by orcutt989** [comment]
You should be able to look up the serial number on any Non-Apple serial number lookup site. Match model and board ID from there. Google "apple serial lookup". 

If you cant do that, then make a bootable Mac OS X usb and do it from there in terminal. If you cant boot to that, then you won't be able yo run AHT anyways.

**Comment by nated099** [comment]
Didn't even think of the bootable OS X. Thanks mate.
