### ISSUE TITLE
error while getting the file ID of /Volumumes/Boot/System/Library/CoreServices/.diagnostics

### ISSUE THREAD

**Issue by limeb** [upekkha/AppleHardwareTest#26]
when running

    sudo bless --folder /Volumes/USBstick/ --file /Volumes/USBstick/System/Library/CoreServices/.diagnostics/diags.efi --label AHT
    error while getting the file ID of /Volumumes/Boot/System/Library/CoreServices/.diagnostics/diags.efi.  Ignoring...

I believe there is a typo on the repo commands.

Manually copying the System files from the mount .dmg to HD/Thumb Drive appears to work.

**Comment by nickcounts** [comment]
I had the same issue when I neglected to change the path `/Volumes/USBstick/` to point to my destination drive. I did this with a (confusingly named) partition AHT, and it worked fine with the following command.

NOTE: There are *two* places that reference your destination path.

1. `--folder /Volumes/USBstick/`
2. `--file /Volumes/USBstick/`

These must both be changed to point to your installation location

```
sudo bless --folder /Volumes/AHT --file /Volumes/AHT/System/Library/CoreServices/.diagnostics/diags.efi --label AHT
```

**Comment by twevin** [comment]
> when running
> 
> ```
> sudo bless --folder /Volumes/USBstick/ --file /Volumes/USBstick/System/Library/CoreServices/.diagnostics/diags.efi --label AHT
> error while getting the file ID of /Volumumes/Boot/System/Library/CoreServices/.diagnostics/diags.efi.  Ignoring...
> ```
> 
> I believe there is a typo on the repo commands.
> 
> Manually copying the System files from the mount .dmg to HD/Thumb Drive appears to work.

** responding to an old thread** 
1st place to start: Volumumes is spelled wrong... 
2nd: I had the same issue with guidance from this [github thread](https://github.com/upekkha/AppleHardwareTest). Fixed the "Ignoring" issue by opening the USB in Finder and adding a Systems folder first and dropped the Library file into there. The "sudo bless" code worked after that and the USB became bootable, but then the following happened = [nothing](https://discussions.apple.com/thread/250285425?page=1) ... I've basically tried everything in this thread and nothing works. Holding down Option and running the USB EFI will quickly run some command lines and then boot back to iOS. I'll save you from reading through 15 pages of [comments](https://discussions.apple.com/thread/250285425?page=1)-- There's a bug that doesn't allow AHT to boot in older Macs and it won't be patched ... Best advice from this is to get 3rd party programs to try and figure out if something is wrong with your hardware. Best of luck to the next person who comes across this!
