### ISSUE TITLE
Combined into one version

### ISSUE THREAD

**Issue by limeblack** [upekkha/AppleHardwareTest#27]
Could these scripts be combined into one bootable version?

**Comment by upekkha** [comment]
Most probably not. The AHT appear to be  hardware-specific. Apple would have to build one big generic test. Alternatively you may have several bootable partitions on a USB Stick with different AHT, but you would have to select the correct one manually at boot time.

**Comment by limeblack** [comment]
@upekkha  that is what I meant multiple partitions(sorry if that wasn't clear).
This would make technicians job a lot easier if there were let's 3 bootable dd images instead how it is currently.
