### ISSUE TITLE
AHT Copy location

### ISSUE THREAD

**Issue by ndguardian** [upekkha/AppleHardwareTest#28]
Hey there!

Quick recommendation for you. In your guide, you recommend users copy from the /Volumes/AHT/System directory to the /Volumes/USBDrive directory. I would recommend copying that to the /Volumes/USBDrive/System, otherwise I find it becomes rather difficult to actually make the drive bootable.

Once I moved the files from /Volumes/USBDrive to /Volumes/USBDrive/System, everything worked just fine.

Anyway, just a recommendation.

**Comment by upekkha** [comment]
Hey,

Thanks for your comment. You are right that the whole System directory needs to be copied to the stick. The cp command with the trailing slash `cp -r /Volumes/AHT/System /Volumes/USBstick/` does exactly that.
