### ISSUE TITLE
Can't create a bootable drive

### ISSUE THREAD

**Issue by iwantnottowant** [upekkha/AppleHardwareTest#29]
Hello!

I follow the instructions step by step I don't get any errors in the terminal. After putting in the command it asks me for my password I put it in and that's all no more messages or anything. Going into disk utility the drive is described as "bootable no" and holding alt while booting up doesn't list the usb drive. I changed names of volumes in the command to match mine. 

Hope I can get some help here :) 
Greetings

**Comment by limeblack** [comment]
Did you try this here https://github.com/upekkha/AppleHardwareTest/issues/26
