### ISSUE TITLE
Apple Hardware Test (AHT) .dmg is EMPTY...   ???

### ISSUE THREAD

**Issue by colinvv** [upekkha/AppleHardwareTest#37]
I just clicked on the appropriate link for my 2012 Mac Pro (MacBookPro9,2 Mac-6F01561E16C75D06).  When the .dmg downloaded I clicked to open it but all that happened was Finder opened a window with a single "System" folder in it.  Inside this there is another single folder called "Library", and inside that there is another single folder called "Core Services".  Inside "Core Services" there is absolutely nothing.  

I expected a new install of the AHT to begin, but instead nothing.  Anyone know what is wrong with the links given in this *solution*?

**Comment by upekkha** [comment]
By default, the Finder does not show hidden items. The keyboard shortcut `Cmd-Shift-.` should toggle the display of hidden files. Otherwise there's also the command `defaults write com.apple.finder AppleShowAllFiles -bool true; killall Finder` to achieve the same.
