### ISSUE TITLE
Mac Mini Late 2014 , Mac Mini 7,1 AHT

### ISSUE THREAD

**Issue by mrusli70** [upekkha/AppleHardwareTest#49]
I have a Mac Mini Late 2014, under Mac Mini 7,1. I did not have a .diagnostic file in macos big sur 11.6.5.

**Comment by upekkha** [comment]
AHT only applies to hardware before 2013. Your hardware is already using [Apple Diagnostics](https://support.apple.com/en-gb/HT202731).

**Comment by mrusli70** [comment]
Oh Thanks! Because i keep having support.apple.com/mac/startup -2002D, 2002F and 5101D errors. And there is no way I can tell as to whether my mac mini late 2014 is the cause of the problems or the my local ISP or got to do with the Apple server.
